metadata_checker actually now checks metadata rather than just validate the apps.

diff --git a/rose-stem/app/metadata_checker/bin/run_macro b/rose-stem/app/metadata_checker/bin/run_macro
--- a/rose-stem/app/metadata_checker/bin/run_macro
+++ b/rose-stem/app/metadata_checker/bin/run_macro
@@ -7,6 +7,31 @@
 
 # META_DIR and JULES_APPS - provided by this app's Rose file extraction.
 META_DIR=$PWD/rose-meta/
+MY_RC=0
+
+# Before validating the apps against the metadata, check that the metadata is
+# valid. jules-lfric and jules-um can be added to the check when they pass.
+export ROSE_META_PATH=$META_DIR
+METADATA=(
+    "jules-fcm-make"
+    "jules-standalone"
+    "rivers-standalone"
+#    "jules-lfric"
+#    "jules-um"
+)
+echo "[INFO] Running rose metadata-check on metadata directories"
+for dir in ${METADATA[@]}; do
+    rose metadata-check -C "$META_DIR"/"$dir"/HEAD
+    RC=$?
+    if [[ $RC -eq 0 ]]; then
+        echo "[OK] $dir"
+    else
+        MY_RC=$RC
+        echo "[FAIL] $dir did not pass metadata-check- see stderr for details"
+        echo "[FAIL] $dir" 1>&2
+    fi
+done
+
 JULES_APPS=$PWD/rose-stem/app
 # APP_DIRS - should either be passed down from suite level or be the input
 # argument to the script.
@@ -15,7 +40,6 @@ JULES_APPS=$PWD/rose-stem/app
 # For example "loobos_* gswp2_*" will run the macro on app directories
 # beginning with loobos or gswp2.
 APP_DIRS=${APP_DIRS:-$@}
-MY_RC=0
 
 echo "[INFO] Running --validate on each app directory"
 for jules_app in $(cd "$JULES_APPS" && ls -d $APP_DIRS); do
@@ -31,5 +55,5 @@ for jules_app in $(cd "$JULES_APPS" && ls -d $APP_DIRS); do
     fi
 done
 
-exit $MY_RC 
+exit $MY_RC
 
